### ISSUE TITLE
Add a button in ideas section to revert to repo's issues

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/Explorer#12]
This is meant for beginner to get started with open-source. Let me know if you need any help :)

**Comment by fharookshaik** [comment]
Hey I would like take this. Please assign it to me..

**Comment by anshuman725** [comment]
> This is meant for beginner to get started with open-source. Let me know if you need any help :)

Hello Kushal
Can you please explain what to do?

**Comment by KushalBhanot** [comment]
Hey, @anshuman725!

Just add a button on the ideas page that reverts back to the repo's issues. Use your creativity and make a PR for the same if interested :)

**Comment by sruthiragupathy** [comment]
Hi, can i work on it?

**Comment by KushalBhanot** [comment]
Sure, @sruthiragupathy! Go ahead. I'll merge the PR with the best updates.
