### ISSUE TITLE
Update the UI of Clubs & Societies section

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/Explorer#16]
I'm not looking for any fancy changes. Just a slight update to make the Clubs & Societies page more visual.

Use your creativity and make a valid PR 😊🙌🏻

Also, make sure you're assigned the issue before making a PR.

**Comment by arhaanb** [comment]
I'd like to try this out. Can you assign it to me?

**Comment by KushalBhanot** [comment]
Sure, @arhaanb! Go ahead. I'm assigning it to you :)

**Comment by fharookshaik** [comment]
Hey I've updated.Please check it out

**Comment by pbisen** [comment]
Could you please assign me? I want to link the images to the official website of the societies at chitkara university.

**Comment by fharookshaik** [comment]
Hey Kushal,

I've made some significant changes to the clubs.html page. Please find them.

Thank You

**Comment by arhaanb** [comment]
I feel like its better to divide them into separate rows instead of having all 4 clubs into a single line. It looks a little more cramped when it's all together. Also, the images seem a little weird, their height and width have both been set so the aspect ratio changed (Making them look squeezed).

**Comment by pbisen** [comment]
Please check, i have added links to the student societies at chitkara. Please check them.

**Comment by pbisen** [comment]
Hey Kushal, 

I have added links to the student societies, please check them.
Thank You
