### ISSUE TITLE
Make the background of the ideas section responsive

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/Explorer#23]

**Comment by NecroTechno** [comment]
Hey there, do you mind if I jump on this issue? :)

Also, this may require a second issue, but it seems that the button is actually transparent and the background is coming through. Is this desired functionality?

**Comment by KushalBhanot** [comment]
Sure, @NecroTechno! Go ahead. 

Raise issues as and when you feel necessary. No, that was not the desired functionality. Feel free to give your own UI/UX touch to it. Looking forward to your PR :) 

I'm assigning it to you.
