### ISSUE TITLE
Update the navbar-brand

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/Explorer#25]
You can either use typography or design one on your own if you know the required skills. It can be text, svg or png.

This issue is only meant for people who have an eye for design and generally work on the front-end side of things.

Use your creativity ✨🤸🏻

**Comment by js899** [comment]
Can I take this issue @KushalBhanot ?

**Comment by Suryam26** [comment]
I would like to work on this

**Comment by js899** [comment]
Kindly assign me on this and let me ask to assure, you want the "E." logo on the left of navbar to be enhanced, right ?

**Comment by KushalBhanot** [comment]
Sure, @js899 and @Suryam26! Go ahead.

Yes, @js899.

**Comment by js899** [comment]
@KushalBhanot please check the navbar-brand and tell if you like it...waiting for your response
