### ISSUE TITLE
Title of each page to be dynamic

### ISSUE THREAD

**Issue by Parth-Gupta10** [KushalBhanot/Explorer#31]
The title of web pages will look good if they are dynamic for example if we are on contact us page it should show "Explorer | Contact us" as the title instead of only "Explorer".

**Comment by KushalBhanot** [comment]
Sounds cool. Do you want to take this up?

**Comment by Parth-Gupta10** [comment]
@KushalBhanot  I have already made the required changes but was unable to edit Ideas.html file

**Comment by agaveyonatan** [comment]
Hi, can i work in this issue? @KushalBhanot

**Comment by agaveyonatan** [comment]
I can use javascript for that issue

**Comment by Parth-Gupta10** [comment]
@KushalBhanot please review my pull request
