### ISSUE TITLE
Text not clearly visible in mobile view (Home Page)

### ISSUE THREAD

**Issue by TeraSurror** [KushalBhanot/Explorer#34]
First of all, I would like to say that the website animations are really cool.

Issues:
Text opacity should be increased in mobile view or background opacity should be decreased.

![Screenshot_Issue](https://user-images.githubusercontent.com/30754252/94984097-2164f680-0566-11eb-9e69-78f707e51668.PNG)

**Comment by TeraSurror** [comment]
Would something like this be fine?
This is only for mobile view. Desktop view looks really good.

![image](https://user-images.githubusercontent.com/30754252/94984461-d0ef9800-0569-11eb-93e1-01043090bf34.png)

**Comment by KushalBhanot** [comment]
Hey, @TeraSurror! 

Nice find! Do you have any other variant of the solution? Maybe just trying changing the opacity of the background or changing the shade of the para. Let me know what you find the best. And commit those into your PR, if they are different than this. I'll merge it after that. Cool?

Best,
Kushal

**Comment by TeraSurror** [comment]
Sure. Will do that!

**Comment by TeraSurror** [comment]
Hey @KushalBhanot 

I have changed the background image opacity. Please check and see which one you like. I will make the PR accordingly.

Opacity 70%
![image](https://user-images.githubusercontent.com/30754252/94986857-c17b4980-057f-11eb-918b-0ba82c0ca7fd.png)

Opacity 50%
![image](https://user-images.githubusercontent.com/30754252/94986868-d3f58300-057f-11eb-8fc0-01383b729569.png)

**Comment by TeraSurror** [comment]
Hey @KushalBhanot 

Instead of changing opacity, I changed the background positioning.

![image](https://user-images.githubusercontent.com/30754252/95094568-abb88080-0747-11eb-9fee-022498163e85.png)

**Comment by TeraSurror** [comment]
Hey @KushalBhanot

I have removed the whitespace.
