### ISSUE TITLE
Change the button on Hero section

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/Explorer#6]
Use your creativity and make it more interactive.

**Comment by KushalBhanot** [comment]
Make sure to add your changes to the `develop` branch.

**Comment by zbarovsky** [comment]
Hi, I'd like to tackle this issue if it's still available?

**Comment by KushalBhanot** [comment]
Sure @zbarovsky, go ahead! I'm assigning it to you 👍🏻
